kernel:
  image: mobylinux/kernel:4.9.x
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/init:12348442d56c2ee9abf13ff38dff2e36b515bd1e
  - mobylinux/runc:b0fb122e10dbb7e4e45115177a61a3f8d68c19a9
  - mobylinux/containerd:18eaf72f3f4f9a9f29ca1951f66df701f873060b
  - mobylinux/ca-certificates:eabc5a6e59f05aa91529d80e9a595b85b046f935
onboot:
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051
  - name: dhcpcd
    image: linuxkit/dhcpcd:f3f5413abb78fae9020e35bd4788fa93df4530b7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:da3138079c168e0c5608d8f3853366c113ed91d2
services:
  - name: rngd
    image: mobylinux/rngd:3dad6dd43270fa632ac031e99d1947f20b22eec9
  - name: prometheus
    image: moby/prom-us-central1-f
    binds:
      - /dev:/dev
      - /var/lib/misc:/data
    capabilities:
      - all
    net: host
trust:
  image:
    - mobylinux/kernel
